name: Build

on: pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: Install packages
        run: yarn install --immutable
      - name: build docs.approvers.dev
        run: yarn run build
      - name: export docs.apprvers.dev
        run: yarn run export
