name: Build

on: pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: pnpm

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.27.0

      - name: Install packages
        run: pnpm install --frozen-lockfile
      - name: build docs.approvers.dev
        run: pnpm build
      - name: export docs.apprvers.dev
        run: pnpm export
